Fix the remaining, frequent flake in the build process.
This is the remaining, common non-deterministic flake that happens
during the image build process. The initial apt-get update sometimes
fails with errors of this type:

```
167.71.86.58] run: apt-get -o DPkg::Lock::Timeout=120 -qqy update
[167.71.86.58] out: E: Could not open file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_jammy-backports_multiverse_cnf_Commands-amd64 - open (2: No such file or directory)
[167.71.86.58] out: Traceback (most recent call last):
[167.71.86.58] out:   File "/usr/lib/cnf-update-db", line 32, in <module>
[167.71.86.58] out:     col.create(db)
[167.71.86.58] out:   File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 95, in create
[167.71.86.58] out:     self._fill_commands(con)
[167.71.86.58] out:   File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 144, in _fill_commands
[167.71.86.58] out:     raise subprocess.CalledProcessError(returncode=sub.returncode,
[167.71.86.58] out: subprocess.CalledProcessError: Command '/usr/lib/apt/apt-helper cat-file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_jammy-backports_multiverse_cnf_Commands-amd64' returned non-zero exit status 100.
[167.71.86.58] out: E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
[167.71.86.58] out: E: Sub-process returned an error code
[167.71.86.58] out:
Fatal error: run() received nonzero return code 100 while executing!
Requested: apt-get -o DPkg::Lock::Timeout=120 -qqy update
```

So far the only approach has been to re-try the build; and eventually
it'd succeed.

command-not-found is not a necessary package and its hook is known to
cause problems on some installation, so we can simply remove it.